version: 2 
jobs: 
  docker_image_build: 
    machine:
      docker_layer_caching: true
    steps: 
      - checkout 
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: Build Docker Image
          command: rake docker
      - run:
          name: Push Docker Image
          command: |
            source env.txt
            docker image tag "$DOCKER_IMAGE_NAME" "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_JOB}-circleci:${CIRCLE_BUILD_NUM}""
            docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_JOB}-circleci:${CIRCLE_BUILD_NUM}"
  debug_qemu_build: 
    docker: 
      - image: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_JOB}-circleci:${CIRCLE_BUILD_NUM}
    resource_class: xlarge
    steps: 
      - checkout 
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive
      - run: 
          name: Build core-image-minimal for qemux86-64
          command: export BITBAKEDIR=sources/poky/bitbake;  MACHINE=qemux86-64 bitbake core-image-minimal

workflows:
  version: 2
  debug-qemu-build:
    jobs:
      - docker_image_build
      - debug_qemu_build:
          requires:
            - docker_image_build