version: 2 
jobs: 
  docker_image_build: 
    machine:
      docker_layer_caching: true
    docker: 
      # DLC does nothing here, its caching depends on commonality of the image layers.
      - image: circleci/ruby:latest
    steps: 
      - checkout
      # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run: rake docker
  debug_qemu_build: 
    machine:
      docker_layer_caching: true
    docker: 
      # DLC does nothing here, its caching depends on commonality of the image layers.
      - image: circleci/ruby:latest
    resource_class: xlarge
    steps: 
      - checkout
      # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run: rake debug:build_qemu

workflows:
  version: 2
  debug-qemu-build:
    jobs:
      - docker_image_build
      - debug_qemu_build:
          requires:
            - docker_image_build