version: 2 
jobs: 
  debug_qemu_build: 
    machine: 
      docker_layer_caching: true
    resource_class: xlarge
    steps: 
      - checkout 
      - run: git submodule update --init --recursive
      # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run: rake debug:build_qemu

workflows:
  version: 2
  debug-qemu-build:
    jobs:
      - debug_qemu_build