version: 2.1
jobs: 
  docker_image_build: 
    machine:
      docker_layer_caching: true
    steps: 
      - checkout 
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: Build Docker Image
          command: rake docker
  debug_qemu_build: 
    docker: 
      - image: pseudodesign/mender-demo-circleci:<< pipeline.number >>
    resource_class: xlarge
    steps: 
      - checkout 
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive
      - run: 
          name: Build core-image-minimal for qemux86-64
          command: |
            export BITBAKEDIR=sources/poky/bitbake
            source sources/poky/oe-init-build-env debug-build
            MACHINE=qemux86-64 bitbake core-image-minimal
  rpi4_dev_build: 
    machine:
      docker_layer_caching: true
    resource_class: xlarge
    steps: 
      - checkout 
      - run:
          name: Checkout Submodules
          command: git submodule update --init --recursive
      - run:
          name: Append Runtime Variables In local.conf
          command: |
            echo "MENDER_ARTIFACT_NAME=dev-circleci-<< pipeline.number >> " >> rpi-build/conf/local.conf
      - run: 
          name: Build core-image-minimal for raspberrypi4-64
          command: |
            rake rpi:build_rpi4_dev
      - store_artifacts:
          path: rpi-build/tmp/deploy

workflows:
  version: 2
  dev-build:
    jobs:
      - docker_image_build:
          filters:
            branches:
              only: 
                - master
      - rpi4_dev_build:
          requires:
            - docker_image_build
          filters:
            branches:
              only:
                - master